version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10  # Replace with the Python version you need
    commands:
      - pip install boto3

  pre_build:
    commands:
      - echo "Nothing to do in the pre_build phase..."
      - yum update -y
      - yum install jq -y
      - pip install requests
      - pip install ruamel.yaml
      
  build:
    commands:
      - echo "Build started"
      - cd bin
      # - python3 main.py & PYTHON_PID=$!; tail -f ../log/scan_automation.log & TAIL_PID=$!; wait $PYTHON_PID; kill $TAIL_PID
      - |
        python3 main.py & PYTHON_PID=$!
        tail -f ../log/scan_automation.log & TAIL_PID=$!
        wait $PYTHON_PID
        kill $TAIL_PID
        # Check for Low severity vulnerabilities in the log file
        if grep -q "Severity: LOW" ../log/scan_automation.log; then
          echo "Low severity vulnerability found. Aborting the pipeline."
          exit 1
        fi


      
