version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10  # Replace with the Python version you need
    commands:
      - pip install boto3

  pre_build:
    commands:
      - echo "Nothing to do in the pre_build phase..."
      - yum update -y
      - yum install jq -y
      - pip install requests
      - pip install ruamel.yaml
      
  build:
    commands:
      - echo "Build started"
      - cd bin
      - set -o pipefail  # Add this to ensure the pipeline fails if the Python script exits with a non-zero status
      - python3 main.py | tee ../log/scan_automation.log
